# Generated by Django 4.1.7 on 2023-04-09 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_author_destination_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='date',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.date'),
        ),
    ]
