# Generated by Django 4.1.7 on 2023-04-09 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_destination_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='date',
        ),
    ]
